/**
 * ReportBuilder Component
 * UI indicator for the report generation phase transition
 *
 * NOTE: This component is a transitional UI state, not the actual report generator.
 * - In Interactive mode: Report is generated by `use-analysis.ts` during analysis
 * - In CI mode: Report is generated by `ci-runner.ts` directly
 *
 * This component shows completion status and signals the XState machine
 * to transition to the final 'done' state.
 *
 * @packageDocumentation
 */

import {Box, Text} from 'ink';
import {useEffect, useRef, useState} from 'react';
import type {ThemeConfig} from '../models/theme.js';

/**
 * Delay before signaling completion to allow UI to render
 * This ensures the success message is visible before exit
 */
const COMPLETION_SIGNAL_DELAY_MS = 100;

/**
 * ReportBuilder component props
 */
export type ReportBuilderProps = {
	/** Theme for styling */
	readonly theme: ThemeConfig;

	/** Callback when report generation completes */
	readonly onComplete: () => void;

	/** Callback when report generation fails */
	readonly onError: (error: Error) => void;
};

/**
 * ReportBuilder component
 * Shows completion status and signals state machine transition
 *
 * The actual report file has already been generated before this component mounts:
 * - Interactive mode: Generated in use-analysis.ts (line ~148)
 * - CI mode: Generated in ci-runner.ts (line ~85)
 */
export function ReportBuilder({
	theme,
	onComplete,
	onError,
}: ReportBuilderProps) {
	const [status, setStatus] = useState<'generating' | 'complete' | 'error'>(
		'generating',
	);
	const hasSignaled = useRef(false);

	useEffect(() => {
		// Prevent double signaling in React StrictMode
		if (hasSignaled.current) {
			return;
		}

		// Signal completion after a brief delay to allow UI to render
		const timer = setTimeout(() => {
			if (hasSignaled.current) {
				return;
			}

			hasSignaled.current = true;

			try {
				setStatus('complete');
				onComplete();
			} catch (error) {
				setStatus('error');
				onError(
					error instanceof Error
						? error
						: new Error('Failed to signal completion'),
				);
			}
		}, COMPLETION_SIGNAL_DELAY_MS);

		return () => {
			clearTimeout(timer);
		};
	}, [onComplete, onError]);

	return (
		<Box flexDirection="column" gap={1}>
			<Text color="green">✓ Analysis complete!</Text>
			{status === 'generating' && (
				<Text color={theme.secondary}>Finalizing report...</Text>
			)}
			{status === 'complete' && (
				<Text color="green">✓ Report generated successfully</Text>
			)}
			{status === 'error' && (
				<Text color="red">✗ Failed to complete report phase</Text>
			)}
		</Box>
	);
}
